### ISSUE TITLE
improve performance of cdx-merge-sort-publish step

### ISSUE THREAD

**Issue by aalsum** [sul-dlss-deprecated/was-crawl-dissemination#14]
Merging and sorting CDX files is not scalable. When the CDX file grows more, the sorting step will take longer time. 
Suggested solution:
- Sort each new CDX file individually.
- Merge the sorted CDX with the main cdx file.

**Comment by drh-stanford** [comment]
We might be able to use `tmpfs` on the VM to improve the performance some -- it's currently ~4GB. -- or use the `-S` flag to specify a larger in memory buffer. The sort command is using the `-u` and `-m` flags.

**Comment by ndushay** [comment]
see jira DEVQUEUE-79

**Comment by ndushay** [comment]
closed as dup.
