### ISSUE TITLE
merge-sort-publish step can't be repeated if it failed

### ISSUE THREAD

**Issue by aalsum** [sul-dlss-deprecated/was-crawl-dissemination#4]
This robot step is modifying the file structure which can't be reversed if there is any failure happened in the middle. My suggestion is to divide it into steps that can be repeated.

**Comment by ndushay** [comment]
if the merges remove dups, it should be repeatable ...

**Comment by ndushay** [comment]
I don't understand why this would be true.  If the druid/WARC specific cdx files hang around, then we can repeat this.  In fact, if we can generate new CDX files from preserved WARC files, then we don't even need the cdx files to repeat ...

**Comment by lmcglohon** [comment]
This issue was moved to sul-dlss/was_robot_suite#27
